server:
  port: 8081

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/gym_auth_db

  security:
    user:
      name: disabled
      password: disabled

jwt:
  secret: 4yPHr8tykGBUnEJ63B2qHzExke8DA2rgdGjaWipbb8pWMX0G1EezaIUDCHnWrIkf
  expiration: 86400000