server:
  port: 8888

spring:
  application:
    name: gym-config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/maida/Desktop/gym-config-repo/
          default-label: master
          search-paths: .


