spring:
  application:
    name: class-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/gym_classes_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

logging:
  level:
    root: INFO
